---
# Tasks for the instance_launcher

 - name: Launch NeCTAR Instances
   shell: python roles/instance_launcher/files/launch_instances.py "{{ numinstances }}"
   register: output
 
 - debug:
     var: output.stdout_lines

 - name: Refresh Inventory
   meta: refresh_inventory

 - name: Add New Instances To "known_hosts"
   shell: ssh-keyscan -H "{{ item }}" >> ~/.ssh/known_hosts
   loop: "{{ groups['all'] }}"
   

