---
# Tasks for the instance_launcher

 - name: Launch NeCTAR Instances
   shell: python roles/instance_launcher/files/launch_instances.py 2
   
 - name: Refresh inventory
   meta: refresh_inventory

 - name: Write the new instances host keys to the known_hosts file
   shell: ssh-keyscan -H "{{ item }}" >> ~/.ssh/known_hosts
   loop: "{{ groups['all'] }}"
   

