---
 #Tasks for the harvester_launcher
   
 - name: Install "python-pip3"
   apt:
     name: python3-pip
     state: latest
     update_cache: yes
     
 - name: Install Required Packages
   pip: 
     name: "{{ item }}"
     state: latest
   loop:
     - shapely
     - textblob
     - tweepy
     - tweet-preprocessor
     - couchdb

 - name: Transfer Scripts To Remote
   copy:
     src: twitharvester.py
     dest: /home/ubuntu/twitharvester.py
    
 - name: Transfer InputFile To Remote
   copy:
     src: allsuburbs.geojson
     dest: /home/ubuntu/allsuburbs.geojson

 - name: Transfer KeywordFiles To Remote
   copy:
     src: keywords
     dest: /home/ubuntu/
     
 - name: Run The Harvester Scripts
   shell: python3 /home/ubuntu/twitharvester.py "{{harvester_id}}" "{{longMin}}" "{{latMin}}" "{{longMax}}" "{{latMax}}" "{{instanceCount}}"
   register: output
 
 - debug:
     var: output.stdout_lines
 
